### ISSUE TITLE
fetchPowerDraw value does not represent the same value in the web GUI

### ISSUE THREAD

**Issue by phillipsnick** [phillipsnick/apc-pdu-snmp#1]
The value is a Guage32 value, not 100% sure on how to convert this into something usable currently.

**Comment by animedbz16** [comment]
This is likely because the value returned is in 10ths of amps.

http://www.observium.org/svn/observer/trunk/mibs/PowerNet-MIB

```
rPDULoadStatusLoad OBJECT-TYPE
   SYNTAX Gauge       
   ACCESS read-only
   STATUS mandatory
   DESCRIPTION
      "Getting this OID will return the phase/bank load measured
       in tenths of Amps."
   ::= { rPDULoadStatusEntry 2 }
```

**Comment by phillipsnick** [comment]
Thanks for this, have pushed a new update for this which now reports the draw correctly for both of my PDUs in amps.

Really should have checked the MIB file, never realised it came with descriptions!
