### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by sloppycoffee** [phillipsnick/apc-pdu-snmp#14]
I am having issues testing your example. I keep getting RequestTimedOutError: Request timed out. 

I logged into my APC pdu, enabled snmpV1 and snmpV3. Not sure if there is anything more needed than that. There are some options for access control but left those default. 

Sitting in the example dir, I am running 'node outlet-info.js'.
I was expecting some output from what it looks like are various queries. 

Any guidance would be helpful in this debug process.

Thanks.

**Comment by phillipsnick** [comment]
I'll try take a look this evening, assuming you set your PDU IP address inside https://github.com/phillipsnick/apc-pdu-snmp/blob/master/examples/config.js

Can you let me know what model you have as well?

**Comment by sloppycoffee** [comment]
Yes, set the IP in the config file. I have two pdus and both not responsive.

The model is:
AP7941

**Comment by phillipsnick** [comment]
Just ran through this (after spending far too long setting the IP on one device).

Steps

Enable SNMPv1
I don't have SNMPv3 enabled, but I tried enabling it and it still works.

```
git clone https://github.com/phillipsnick/apc-pdu-snmp.git
cd apc-pdu-snmp
npm install
cd examples
```

Edited examples/config.js to match PDU IP.

```
node outlet-info.js
```

Test with AP7920

```
➜  examples git:(master) ✗ node outlet-info.js
Total outlets: 8
Outlet name for port 1 is: SW1
Outlet 1 is currently: Off
Power draw is currently: 0 amps
Low warning threshold is 0 amps
Near overload warning threshold is, 8 amps
Overload alarm threshold is 10 amps
RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.2.3.1.1.3.0
All outlet names: { '1': 'SW1',
  '2': 'SW2',
  '3': 'SW3',
  '4': 'SW4',
  '5': 'BB1',
  '6': 'BB2',
  '7': 'BB3',
  '8': 'Outlet 8' }
```

Test on AP7952

```
➜  examples git:(master) node outlet-info.js
Total outlets: 24
Outlet name for port 1 is: Outlet 1
Outlet 1 is currently: Off
Power draw is currently: 0 amps
Low warning threshold is 0 amps
Near overload warning threshold is, 11 amps
Overload alarm threshold is 12 amps
The current load state is bankLoadNormal ( 1 )
All outlet names: { '1': 'Outlet 1',
  '2': 'KVM',
  '3': 'Outlet 3',
  '4': 'Outlet 4',
  '5': 'Outlet 5',
  '6': 'Outlet 6',
  '7': 'Outlet 7',
  '8': 'Outlet 8',
  '9': 'Outlet 9',
  '10': 'Fans (temp)',
  '11': 'Monitor',
  '12': 'Outlet 12',
  '13': 'Outlet 13',
  '14': 'Outlet 14',
  '15': 'Dell 5524 (2/3)',
  '16': 'Outlet 16',
  '17': 'Outlet 17',
  '18': 'Workstation',
  '19': 'Shelf/VM',
  '20': 'Outlet 20',
  '21': 'Outlet 21',
  '22': 'Outlet 22',
  '23': 'Node 2',
  '24': 'UPS' }
```

Not too sure why you are having this issue, what versions are your PDUs running?

AP7920

```
Application Module

Name:    rpdu
Version:    v3.7.0
Date:    01/13/2009
Time:    15:30:40

APC OS (AOS)

Name:    aos
Version:    v3.7.0
Date:    01/13/2009
Time:    14:17:08
```

AP7952

```
Application Module

Name:	rpdu
Version:	v3.5.5
Date:	07/18/2007
Time:	11:38:29

APC OS (AOS)

Name:	aos
Version:	v3.5.6
Date:	07/18/2007
Time:	10:24:55
```

**Comment by sloppycoffee** [comment]
Same result. Time out. Followed your steps. I tried without v3 turned on. Still nothing. Did you change anything under snmpv1 access control?

Here is the version I am running:
Application Module
 	 
Name:	rpdu
Version:	v3.5.7
Date:	03/17/2008
Time:	13:24:04
 
 	 	 
 	
APC OS (AOS)
 	 
Name:	aos
Version:	v3.5.8
Date:	03/17/2008
Time:	11:51:00

**Comment by phillipsnick** [comment]
This is my SNMPv1 access control screen.

<img width="754" alt="screen shot 2017-09-08 at 11 44 44" src="https://user-images.githubusercontent.com/2021654/30208404-2fb9c0de-948b-11e7-935f-0e1ffffde4f2.png">

**Comment by sloppycoffee** [comment]
Success! Changed the community names and got output!

I am now getting some sort of error. You know what this means?

Total outlets: 24
Outlet name for port 1 is: Outlet 1
Outlet 1 is currently: On
Power draw is currently: 14.2 amps
RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.2.2.1.1.2.1
RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.2.2.1.1.3.1
RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.2.2.1.1.4.1
RequestFailedError: NoSuchName: 1.3.6.1.4.1.318.1.1.12.2.3.1.1.3.0


edit:

Looking at it, it appears to be related to loadThreshold. I don't think I need that info for this project so I think this is working. 

Side note, do you know how to tell exactly what voltage the PDU is running at? 208v, 220v, 230v, 240v?

**Comment by phillipsnick** [comment]
Nice! 

Does that particular model not have load monitoring?

I haven't found anything to display the voltage, if there's something in your web interface then there might be a MIB for your particular model? I personally use my UPS to pull the voltage into monitoring.

**Comment by sloppycoffee** [comment]
Under device manager, load management, configuratition, there are these options:

Overload Alarm Threshold: | Amps | Amps | Amps
-- | -- | -- | --
Near Overload Warning Threshold: | Amps | Amps | Amps
Low Load Warning Threshold:

Are those the values you are querying? I think I can actually use a multi meter to check the voltage. There isn't a way to get more decimal points for the amps? Looks like that is a limitation of the pdu?

I am trying to gather power used over the course of the month.

**Comment by phillipsnick** [comment]
Yep thats it. The calls for these are form line 57 onwards here: https://github.com/phillipsnick/apc-pdu-snmp/blob/master/examples/outlet-info.js#L57

I haven't seen anything on the PDU, maybe the newer models have this?
My APC UPS does a better job of this as it reports in Kwh consumed per month.  

For power monitoring I use a combination a few methods, clamp meter on the meter tail and the TP-Link HS110 (13A only).

**Comment by sloppycoffee** [comment]
Those are both options I will look into. My PDUs are plugged into 240v, so I need a TP-link that can track power usage. The HS110 is 110v.

Thanks for all the help.
