### ISSUE TITLE
README - APC MIB link

### ISSUE THREAD

**Issue by animedbz16** [phillipsnick/apc-pdu-snmp#3]
In the readme it looks like your refering to this link for the APC MIB (http://www.observium.org/svn/observer/trunk/mibs/PowerNet-MIB). This MIB appears to be version 4.0.5 (Jan 11, 2012) and is out of date.

Latest APC mibs can be found on their website here:
ftp://ftp.apc.com/apc/public/software/pnetmib/mib

Current MIB (May 12 2014):
ftp://ftp.apc.com/apc/public/software/pnetmib/mib/411/powernet411.mib

**Comment by phillipsnick** [comment]
Updated cheers
